server:
  servlet:
    context-path: /springai

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
#    google:
#      genai:
#        api-key: ${GOOGLE_GENAI_API_KEY}
#        chat:
#          options:
#            model: gemini-2.5-flash
#    ollama:
#      chat:
#        options:
#          model: llama3

    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: https://cortex.aws.lmig.com/rest/v2/azure
        embedding:
          options:
            model: text-embedding-3-small-v1
#            deployment-name: text-embedding-ada-002
        chat:
          options:
            model: gpt-4o-2024-05-13
        image:
#          api-key: ${AZURE_OPENAI_API_KEY}
          options:
            quality: hd
            model: dall-e-3 # or dall-e-3
        custom-headers:
          use-case: spring-ai
      vectorstore:
        pgvector:
          initialize-schema: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/docs
    username: admin
    password: password
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
      validationQuery: SELECT 1
  flyway:
    enabled: false
ingestion:
  enabled: false

logging:
  level:
    org:
      springframework:
        ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

currency-exchange:
  api-key: ${CURRENTENCY_API_KEY}
  base-url: https://openexchangerates.org/api

weather:
  api-key: ${WEATHER_API_KEY}
  api-url: https://api.weatherapi.com/v1